name: Release Pipeline

on:
  push:
    tags: [ "lupa-*" ]

jobs:
  wheels:
    uses: ./.github/workflows/wheels.yml

  pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Download lupa wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Download lupa sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
