name: Wheel build

on:
  release:
    types: [created]
  push:
    paths:
      - .github/workflows/wheels.yml
      - requirements.txt
      - pyproject.toml
      - MANIFEST.in
      - Makefile
      - setup*
      - build*
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/wheels.yml
      - requirements.txt
      - pyproject.toml
      - MANIFEST.in
      - Makefile
      - setup*
      - build*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  sdist:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Check out recursively
      run: git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Build sdist
      run: python setup.py sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  generate-wheels-matrix:
    name: Generate wheels matrix
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v4
      - name: Install cibuildwheel
        # Nb. keep cibuildwheel version pin consistent with job below
        run: pipx install cibuildwheel==2.21.3
      - id: set-matrix
        run: |
          MATRIX=$(
            {
              cibuildwheel --print-build-identifiers --platform windows \
              | jq -nRc '{"only": inputs, "os": "windows-2019"}'
            } | jq -sc
          )
          echo "include=$MATRIX"
          echo "include=$MATRIX" >> $GITHUB_OUTPUT

  build_wheels:
    name: Build for ${{ matrix.only }}
    needs: generate-wheels-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-wheels-matrix.outputs.include) }}

    env:
      MACOSX_DEPLOYMENT_TARGET: '11.0'
      LUPA_WITH_LUA_DLOPEN: ${{ startsWith(matrix.os, 'windows') && 'false' || 'true' }}

    steps:
      - uses: actions/checkout@v4

      - name: Check out recursively
        run: git submodule update --init --recursive

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install MacOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install automake libtool
          ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize

      - name: Setup Visual Studio for x64
        if: contains(matrix.os, 'windows') && contains(matrix.only, 'win_amd64')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Setup Visual Studio for x86
        if: contains(matrix.os, 'windows') && contains(matrix.only, 'win32')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x86

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        with:
          only: ${{ matrix.only }}

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheel-${{ matrix.only }}

  upload_release_assets:
    name: Upload Release Wheels
    needs: [ build_wheels, sdist ]
    runs-on: ubuntu-latest

    permissions:
      contents: write  # to create GitHub release (softprops/action-gh-release)

    steps:
      - name: Download bdist files
        uses: actions/download-artifact@v4
        with:
          path: ./bdist_downloads
          merge-multiple: true

      - name: List downloaded artifacts
        run: ls -la ./bdist_downloads

      - uses: actions/upload-artifact@v4
        with:
          path: ./bdist_downloads/*.whl
          name: wheels

  make_release:
    name: Make Github release
    needs: [ upload_release_assets ]
    runs-on: ubuntu-latest

    permissions:
      contents: write  # to create GitHub release (softprops/action-gh-release)

    steps:
      - name: Download lupa wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Download lupa sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*

  pypi:
    name: Upload release to PyPI
    needs: [ upload_release_assets ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Download lupa wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Download lupa sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
